# Définition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template

[[routes]]
url = ""
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "jouer"
controleur = "controleurs/jouer.py"
template = "jouer.html"

[[routes]]
url = "grille_aleatoire"
controleur = "controleurs/grille_aleatoire.py"
template = "grille_aleatoire.html"

[[routes]]
url = "historique"
controleur = "controleurs/historique.py"
template = "historique.html"

[[routes]]
url = "ajouter"
controleur = "controleurs/ajouter.py"
template = "ajouter.html"
